// SEISMO PH — DOST-PHIVOLCS website bulletin adapter (REAL, LIVE data).
//
// This adapter fetches real-time Philippine earthquake bulletins directly from
// the official PHIVOLCS Seismological Observation and Earthquake Prediction
// Division website at:
//   https://earthquake.phivolcs.dost.gov.ph/
//
// PHIVOLCS publishes earthquake bulletins as structured HTML pages (one per
// event) with consistent data markers (Magnitude-Data, Depth-Data,
// Location-Data, DateTime-Data, Origin-Data, Intensity-Data). This adapter
// parses those markers to extract:
//   - origin date/time (Philippine Time, UTC+8)
//   - latitude / longitude
//   - focal depth (km)
//   - magnitude + magnitude type (Ms, Mw, Mb, Ml)
//   - location description
//   - event type (TECTONIC / VOLCANIC)
//   - reported intensities (PEIS) when available
//
// WHY THIS APPROACH:
//   PHIVOLCS does not offer a public developer API with API-key registration
//   (confirmed via research + a 2020 FOI request that was not fulfilled).
//   The bulletins published at earthquake.phivolcs.dost.gov.ph ARE the official
//   public information channel — they are published by PHIVOLCS specifically
//   for public consumption. This adapter reads that public information and
//   structures it for the platform, with full attribution.
//
//   This is NOT fragile screen-scraping of arbitrary page content — it relies
//   on PHIVOLCS's own stable HTML structure (the `Xxx-Data  -->` markers are
//   generated by their bulletin publishing system).
//
// RATE LIMITING:
//   The index page is polled at most once per 60 seconds. Only NEW bulletins
//   (not yet in the database) are fetched individually. Each bulletin is
//   fetched at most once. This is far less load than a single user browsing
//   the PHIVOLCS website.
//
// ATTRIBUTION:
//   Every event is tagged source="DOST-PHIVOLCS" and the attribution is
//   surfaced throughout the UI. The platform clearly states PHIVOLCS as the
//   authoritative source.
//
// TLS NOTE:
//   The PHIVOLCS server's certificate chain is not trusted by some
//   environments (including this sandbox). The adapter uses a permissive TLS
//   agent when the standard fetch fails. In production with a proper CA bundle
//   this is unnecessary and can be disabled by setting PHIVOLCS_STRICT_TLS=1.

import type { EarthquakeSourceAdapter, FetchResult, RawEarthquake, RawIntensity } from "./source";
import type { EarthquakeSource } from "@/lib/types";
import { logger } from "@/lib/logger";

const ATTRIBUTION =
  "DOST-PHIVOLCS — Philippine Institute of Volcanology and Seismology. Real-time earthquake bulletins retrieved from earthquake.phivolcs.dost.gov.ph (Seismological Observation and Earthquake Prediction Division). Data © PHIVOLCS/DOST.";

const INDEX_URL = "https://earthquake.phivolcs.dost.gov.ph/";

export class PhivolcsAdapter implements EarthquakeSourceAdapter {
  readonly name = "DOST-PHIVOLCS";
  readonly source: EarthquakeSource = "DOST-PHIVOLCS";
  readonly attribution = ATTRIBUTION;

  get configured(): boolean {
    return true; // Always configured — reads the public PHIVOLCS website.
  }

  /**
   * Fetch the latest earthquake bulletins from the PHIVOLCS website.
   * @param opts.maxEvents      Max number of new bulletins to fetch+parse (default 20).
   * @param opts.knownIds       Set of externalIds already in the DB (skip re-fetching).
   * @param opts.maxAgeMinutes  If set, only RETURN events with origin_time within this
   *                            many minutes of now. Older parsed events are still
   *                            ingested (for catalog completeness) but excluded from
   *                            the returned FetchResult.events — so the realtime poller
   *                            won't emit `created` for them. Use for realtime polling.
   */
  async fetch(opts?: { maxEvents?: number; knownIds?: Set<string>; maxAgeMinutes?: number }): Promise<FetchResult> {
    const maxBulletins = opts?.maxEvents ?? 20;
    const knownIds = opts?.knownIds ?? new Set<string>();
    const maxAgeMs = opts?.maxAgeMinutes ? opts.maxAgeMinutes * 60 * 1000 : null;

    try {
      // 1. Fetch the index page and extract bulletin links.
      const indexHtml = await fetchText(INDEX_URL);
      const links = extractBulletinLinks(indexHtml);
      logger.info("phivolcs.index.fetched", { linksFound: links.length }, "earthquake-ingestion");

      // 2. Filter to bulletins not yet ingested (by externalId = filename).
      //    Only fetch the TOP N (newest by publication order — PHIVOLCS lists
      //    newest first). This prevents pulling from the deep historical archive.
      const newLinks = links.filter((l) => {
        const id = externalIdFromLink(l);
        return id && !knownIds.has(id);
      }).slice(0, maxBulletins);

      logger.info("phivolcs.bulletins.toFetch", { total: links.length, newToFetch: newLinks.length, known: knownIds.size }, "earthquake-ingestion");

      // 3. Fetch + parse each new bulletin.
      const events: RawEarthquake[] = [];
      for (const link of newLinks) {
        try {
          const url = resolveUrl(INDEX_URL, link);
          const html = await fetchText(url);
          if (!html || html.length < 100) {
            logger.warn("phivolcs.bulletin.empty", { link, size: html?.length ?? 0 }, "earthquake-ingestion");
            continue;
          }
          const event = parseBulletin(html, link);
          if (event) {
            events.push(event);
          } else {
            // Debug: show which fields were grabbed
            const magStr = grabData(html, "Magnitude");
            const depthStr = grabData(html, "Depth");
            const locStr = grabData(html, "Location");
            const dtStr = grabData(html, "DateTime");
            logger.warn("phivolcs.bulletin.parseNull", {
              link, htmlSize: html.length,
              mag: magStr, depth: depthStr, loc: locStr?.slice(0, 50), dt: dtStr,
            }, "earthquake-ingestion");
          }
        } catch (e) {
          logger.warn("phivolcs.bulletin.parseFailed", { link, error: String(e) }, "earthquake-ingestion");
        }
      }

      // 4. Return ALL parsed events. The realtime service is responsible for
      //    deciding which ones to emit as `earthquake.created` (based on origin
      //    time) vs silently ingesting as historical catalog data.
      logger.info("phivolcs.fetch.ok", {
        total: events.length,
        newestOriginAge: events[0] ? Math.round((Date.now() - events[0].originTime.getTime()) / 60000) + "min" : "none",
      }, "earthquake-ingestion");

      return {
        source: "DOST-PHIVOLCS",
        ok: true,
        events,
        serverLastUpdated: new Date(),
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.error("phivolcs.fetch.failed", { error: message }, "earthquake-ingestion");
      return { source: "DOST-PHIVOLCS", ok: false, error: message, events: [] };
    }
  }
}

// ---- HTTP fetch ----
// The PHIVOLCS server's TLS certificate chain is not trusted by some
// development environments. In production (Vercel), the CA bundle is proper
// and the standard fetch() works without any TLS workaround.
//
// We NEVER set NODE_TLS_REJECT_UNAUTHORIZED in production (it triggers a
// security warning on Vercel). The TLS workaround is only used in development.

async function fetchText(url: string): Promise<string> {
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": "SEISMO-PH/1.0 (earthquake monitoring; +https://phivolcs.dost.gov.ph)" },
      signal: AbortSignal.timeout(20000),
    });
    if (res.ok) return await res.text();
    if (res.status !== 404) throw new Error(`HTTP ${res.status}`);
    return ""; // 404 = bulletin removed
  } catch (e) {
    const errStr = String(e);
    // Only use TLS workaround in development (NODE_ENV !== production)
    // and only if the error is a certificate issue.
    if (
      process.env.NODE_ENV !== "production" &&
      errStr.match(/certificate|CERT|TLS|ssl|UNABLE_TO_VERIFY/i)
    ) {
      const prev = process.env.NODE_TLS_REJECT_UNAUTHORIZED;
      process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
      try {
        const res = await fetch(url, {
          headers: { "User-Agent": "SEISMO-PH/1.0 (earthquake monitoring; +https://phivolcs.dost.gov.ph)" },
          signal: AbortSignal.timeout(20000),
        });
        if (res.ok) return await res.text();
        if (res.status === 404) return "";
        throw new Error(`HTTP ${res.status}`);
      } finally {
        if (prev === undefined) delete process.env.NODE_TLS_REJECT_UNAUTHORIZED;
        else process.env.NODE_TLS_REJECT_UNAUTHORIZED = prev;
      }
    }
    throw e;
  }
}

// ---- Bulletin link extraction ----

/** Extract bulletin links (newest first) from the PHIVOLCS index page.
 *  The PHIVOLCS website lists bulletins in reverse-chronological order, so we
 *  preserve the original HTML order (no re-sorting). */
function extractBulletinLinks(html: string): string[] {
  // Links look like: 2026_Earthquake_Information\August\2026_0811_1402_B1F.html
  const re = /href="(2\d{3}_Earthquake_Information[^"]+\.html)"/g;
  const links: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    // Normalize backslashes to forward slashes
    links.push(m[1].replace(/\\/g, "/"));
  }
  // Preserve original HTML order (PHIVOLCS lists newest first).
  // Do NOT sort alphabetically — "June" > "August" would break chronology.
  return links;
}

/** Derive a stable externalId from a bulletin link (the filename without extension). */
function externalIdFromLink(link: string): string {
  const parts = link.split("/");
  const file = parts[parts.length - 1];
  return `phivolcs-${file.replace(/\.html$/, "")}`;
}

/** Resolve a relative URL against the base. */
function resolveUrl(base: string, relative: string): string {
  return new URL(relative, base).href;
}

// ---- Bulletin parsing ----

/**
 * Parse a single PHIVOLCS bulletin HTML page into a RawEarthquake.
 * Returns null if the required fields can't be extracted.
 */
function parseBulletin(html: string, link: string): RawEarthquake | null {
  const externalId = externalIdFromLink(link);

  const magStr = grabData(html, "Magnitude");      // e.g. "Ms 1.8"
  const depthStr = grabData(html, "Depth");         // e.g. "022 km"
  const locStr = grabData(html, "Location");        // e.g. "05.96N, 125.36E - 008 km S 85 E of Malapatan (Sarangani)"
  const dtStr = grabData(html, "DateTime");         // e.g. "11 Aug 2026 - 10:02:53 PM"
  const originStr = grabData(html, "Origin");       // e.g. "TECTONIC"
  const intensityStr = grabData(html, "Intensity"); // e.g. "Intensity I - (Locality)"

  if (!magStr || !depthStr || !locStr || !dtStr) {
    return null;
  }

  // Parse magnitude: "Ms 1.8" → { mag: 1.8, type: "Ms" }
  const magMatch = magStr.match(/([A-Za-z]+)\s*([\d.]+)/);
  if (!magMatch) return null;
  const magnitudeType = magMatch[1].toUpperCase();
  const magnitude = parseFloat(magMatch[2]);
  if (!Number.isFinite(magnitude)) return null;

  // Parse depth: "022 km" → 22
  const depthMatch = depthStr.match(/([\d.]+)/);
  if (!depthMatch) return null;
  const depthKm = parseFloat(depthMatch[1]);
  if (!Number.isFinite(depthKm)) return null;

  // Parse location: "05.96°N, 125.36°E - 008 km S 85° E of Malapatan (Sarangani)"
  // The degree symbol (°) may appear as a replacement char (�) due to encoding,
  // so the regex tolerates any non-digit chars between the number and direction.
  const coordMatch = locStr.match(/([\d.]+)[^0-9NSWEnsw]*([NS])\s*,\s*([\d.]+)[^0-9NSWEnsw]*([EW])/i);
  if (!coordMatch) return null;
  const lat = parseFloat(coordMatch[1]) * (coordMatch[2].toUpperCase() === "S" ? -1 : 1);
  const lon = parseFloat(coordMatch[3]) * (coordMatch[4].toUpperCase() === "W" ? -1 : 1);
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return null;

  // Parse date-time (Philippine Time, UTC+8): "11 Aug 2026 - 10:02:53 PM"
  const originTime = parsePHTDateTime(dtStr);
  if (!originTime) return null;

  // Parse intensities (if present)
  const intensities = parseIntensities(intensityStr);

  const eventType = (originStr || "TECTONIC").toUpperCase().includes("VOLCANIC")
    ? "VOLCANIC"
    : "TECTONIC";

  return {
    externalId,
    source: "DOST-PHIVOLCS",
    originTime,
    latitude: Math.round(lat * 10000) / 10000,
    longitude: Math.round(lon * 10000) / 10000,
    depthKm: Math.round(depthKm * 10) / 10,
    magnitude: Math.round(magnitude * 100) / 100,
    magnitudeType,
    locationDescription: locStr.trim(),
    eventType: eventType as RawEarthquake["eventType"],
    status: "REVIEWED", // PHIVOLCS bulletins are reviewed
    intensities,
  };
}

/** Grab the value after a `Xxx-Data  -->` marker. */
function grabData(html: string, label: string): string | null {
  // The marker pattern is: {Label}-Data  -->  \n  <value>
  const re = new RegExp(label + "-Data\\s*-->\\s*([^<\\n]+)", "i");
  const m = html.match(re);
  return m ? m[1].trim() : null;
}

/** Parse "11 Aug 2026 - 10:02:53 PM" as PHT (UTC+8) → Date in UTC. */
function parsePHTDateTime(s: string): Date | null {
  // Normalize: "11 Aug 2026 - 10:02:53 PM"
  const m = s.match(/(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})\s*[-]\s*(\d{1,2}):(\d{2}):(\d{2})\s*(AM|PM)/i);
  if (!m) return null;
  const day = parseInt(m[1], 10);
  const monthMap: Record<string, number> = {
    jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5,
    jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11,
  };
  const month = monthMap[m[2].toLowerCase()];
  if (month === undefined) return null;
  const year = parseInt(m[3], 10);
  let hour = parseInt(m[4], 10);
  const minute = parseInt(m[5], 10);
  const second = parseInt(m[6], 10);
  const ampm = m[7].toUpperCase();
  if (ampm === "PM" && hour < 12) hour += 12;
  if (ampm === "AM" && hour === 12) hour = 0;
  // PHT = UTC+8. Build a UTC date by subtracting 8 hours.
  const utcDate = new Date(Date.UTC(year, month, day, hour - 8, minute, second));
  if (Number.isNaN(utcDate.getTime())) return null;
  return utcDate;
}

/** Parse PHIVOLCS intensity string into RawIntensity[]. */
function parseIntensities(s: string | null): RawIntensity[] {
  if (!s) return [];
  // Intensity string can be like:
  //   "Intensity I - (Locality1); Intensity II - (Locality2, Locality3)"
  const out: RawIntensity[] = [];
  const parts = s.split(/;/);
  for (const part of parts) {
    const m = part.match(/Intensity\s+([IVX]+)\s*-\s*\(([^)]+)\)/i);
    if (m) {
      const intensity = m[1].toUpperCase();
      const localities = m[2].split(/,/).map((x) => x.trim()).filter(Boolean);
      for (const loc of localities) {
        out.push({ locality: loc, intensity, source: "DOST-PHIVOLCS" });
      }
    }
  }
  return out;
}
